name: Update on server

on: workflow_dispatch

jobs:
  update-server:
    name: Update on server
    runs-on: ubuntu-latest
    env:
      FOO: "v"  # TODO: use version tag here
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script_stop: true
        script: |
          sudo ~/callupdate.sh
